# Build TileDB-SOMA readthedocs site: https://tiledbsoma.readthedocs.io
# Build history can be found at https://readthedocs.org/projects/tiledbsoma/builds
version: 2
sphinx:
  configuration: doc/source/conf.py
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install --upgrade pip
    - doc/build.sh -r -V  # install deps, don't make a venv
