# Build TileDB-SOMA readthedocs site: https://tiledbsoma.readthedocs.io
# Build history can be found at https://readthedocs.org/projects/tiledbsoma/builds
version: 2
sphinx:
  configuration: doc/source/conf.py
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  apt_packages:
    - build-essential
    - cmake
    - git
  commands:
    - pip install --upgrade pip
    - git clone https://github.com/microsoft/vcpkg.git vcpkg && ./vcpkg/bootstrap-vcpkg.sh
    - CMAKE_TOOLCHAIN_FILE=$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake doc/build.sh -r -V