project:
  type: website
  output-dir: docs

format:
  html:
    toc: true
    theme: 
      light: [flatly, "quarto-materials/tiledb.scss"]
    # TODO: Inter font needs custom font-install for CI
    #mainfont: Inter
    mainfont: Helvetica
    fontsize: 1rem
    linkcolor: "#4d9fff"
    code-copy: true
    code-overflow: wrap
    css: "quarto-materials/tiledb.css"

website:
  favicon: "images/favicon.ico"
  site-url: https://tiledb-singlecell-docs.s3.amazonaws.com/docs/overview.html
  repo-url: https://github.com/single-cell-data/TileDB-SingleCell
  # We may want one or both of these, or neither:
  repo-actions: [edit, issue]
  page-navigation: true
  navbar:
    background: light
    logo: "quarto-materials/tiledb-logo.png"
    collapse-below: lg
    left:
      - text: "Home page"
        href: "https://tiledb.com"
      - text: "Login"
        href: "https://cloud.tiledb.com/auth/login"
      - text: "Contact us"
        href: "https://tiledb.com/contact"
      - text: "Repo"
        href: "https://github.com/single-cell-data/TileDB-SingleCell"

  sidebar:
    - style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: "overview.md"
          text: "Overview"

        - section: "R"
          contents:
            - href: "https://tiledb-inc.github.io/tiledbsc/reference/index.html"
              text: "R API"
            - href: "https://tiledb-inc.github.io/tiledbsc/articles/introduction.html"
              text: "R examples"

        - section: "Python"
          contents:

            - section: "Python examples"
              contents:
                - href: "apis/python/examples/obtaining-data-files.md"
                  text: "Obtaining data files"
                - href: "apis/python/examples/ingesting-data-files.md"
                  text: "Ingesting data files"
                - href: "apis/python/examples/anndata-and-tiledb.md"
                  text: "Comparing AnnData and TileDB files"
                - href: "apis/python/examples/inspecting-schema.md"
                  text: "Inspecting SOMA schemas"
                - href: "apis/python/examples/soma-collection-reconnaissance.md"
                  text: "SOMA-collection reconnaissance"

            - section: "Python API"
              contents:
                - href: "apis/python/doc/overview.md"

                - href: "apis/python/doc/soma_collection.md"
                  text: "SOMACollection"
                - href: "apis/python/doc/soma.md"
                  text: "SOMA"

                - href: "apis/python/doc/soma_options.md"
                  text: "SOMAOptions"

                - href: "apis/python/doc/assay_matrix_group.md"
                  text: "AssayMatrixGroup"
                - href: "apis/python/doc/assay_matrix.md"
                  text: "AssayMatrix"
                - href: "apis/python/doc/annotation_dataframe.md"
                  text: "AnnotationDataFrame"
                - href: "apis/python/doc/annotation_matrix_group.md"
                  text: "AnnotationMatrixGroup"
                - href: "apis/python/doc/annotation_matrix.md"
                  text: "AnnotationMatrix"
                - href: "apis/python/doc/annotation_pairwise_matrix_group.md"
                  text: "AnnotationPairwiseMatrixGroup"
                - href: "apis/python/doc/raw_group.md"
                  text: "RawGroup"
                - href: "apis/python/doc/uns_group.md"
                  text: "UnsGroup"
                - href: "apis/python/doc/uns_array.md"
                  text: "UnsArray"

                - href: "apis/python/doc/tiledb_array.md"
                  text: "TileDBArray"
                - href: "apis/python/doc/tiledb_group.md"
                  text: "TileDBGroup"
                - href: "apis/python/doc/tiledb_object.md"
                  text: "TileDBObject"

                - href: "apis/python/doc/util.md"
                  text: "tiledbsc.util"
                - href: "apis/python/doc/util_ann.md"
                  text: "tiledbsc.util_ann"
                - href: "apis/python/doc/util_tiledb.md"
                  text: "tiledbsc.util_tiledb"
