#!/usr/bin/env python3

# ================================================================
# Prints a table providing details about the fragments of an array.
# ================================================================

import argparse

import pandas as pd

import tiledb


def list_fragments(array_uri: str) -> None:
    print(f"Listing fragments for array: '{array_uri}'")
    vfs = tiledb.VFS()

    fragments = []
    fi = tiledb.fragment.FragmentInfoList(array_uri=array_uri)

    for f in fi:
        f_dict = {
            "array_schema_name": f.array_schema_name,
            "num": f.num,
            "cell_num": f.cell_num,
            "size": vfs.dir_size(f.uri),
        }

        # parse nonempty domains into separate columns
        for d in range(len(f.nonempty_domain)):
            f_dict[f"d{d}"] = f.nonempty_domain[d]

        fragments.append(f_dict)

    frags_df = pd.DataFrame(fragments)
    print(frags_df)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument(
        "array_uri",
        type=str,
        help="URI of the array to list fragments for",
    )
    args = p.parse_args()
    list_fragments(args.array_uri)


if __name__ == "__main__":
    main()
