#!/usr/bin/env bash

#set -eux pipefail

# cd to the top level directory of the repo
cd $(git rev-parse --show-toplevel)

# set env for cmake
export pybind11_DIR=$(python -m pybind11 --cmakedir)

rm -rf build dist
cmake -B build -S libtiledbsc
#cmake -B build -S libtiledbsc -DCMAKE_BUILD_TYPE=Debug

cmake --build build --target check-format
cmake --build build --config Release -j $(nproc)
cmake --build build --target install-libtiledbsc
