#!/usr/bin/env bash

#
# A script to remove data generated by `prepare-test-data.sh`. Make sure to update
# this script after adding new dat to `prepare-test-data.sh`.
#
# See ../data/README.md for instructions on updating this script with new data.

set -euo pipefail

# Change directory to the `data` folder.
cd "$(dirname "$0")/../data"

# Remove prepared test data.
rm -rf soco
rm -rf example-visium-v2 example-visium-v1
rm -rf soma-experiment-versions
