#!/usr/bin/env bash

set -euo pipefail

# cd to the top level directory of the repo
cd $(git rev-parse --show-toplevel)

# create and activate venv
python -m venv test/tiledbsoma
if [ ${OSTYPE} == "msys" ]; then # windows
  source test/tiledbsoma/Scripts/activate
else
  source test/tiledbsoma/bin/activate
fi

# build
pip install -v -e apis/python

# check
python -c "import tiledbsoma.libtiledbsoma; print(tiledbsoma.libtiledbsoma.version())"

# install test data
./apis/python/tools/ingestor \
  --ifexists replace \
  --soco \
  -o test/soco \
  -n \
  data/pbmc3k_processed.h5ad \
  data/10x-pbmc-multiome-v1.0/subset_100_100.h5ad

# test
pip install pytest
pytest -v --durations=0 libtiledbsoma

printf "\n\nActivate the tiledbsoma venv with this command:\n"
printf "\n    source test/tiledbsoma/bin/activate\n\n"
