#!/usr/bin/env bash

set -euo pipefail

# cd to the top level directory of the repo
cd $(git rev-parse --show-toplevel)

# create and activate venv
python -m venv test/tiledb_test
. test/tiledb_test/bin/activate

# install python api and dependencies
cd apis/python
python -m pip install .

# ingest test data into soco/soma
cd -
./apis/python/tools/ingestor \
  --soco \
  -o test/soco \
  -n \
  data/pbmc3k_processed.h5ad \
  data/10x-pbmc-multiome-v1.0/subset_100_100.h5ad
