#!/usr/bin/env bash

set -euo pipefail

# cd to the top level directory of the repo
cd $(git rev-parse --show-toplevel)

# create and activate venv
python -m venv test/tiledbsoma
source test/tiledbsoma/bin/activate

# clean
rm -rf build dist
rm -f apis/python/src/tiledbsoma/libtiledb.*
rm -f apis/python/src/tiledbsoma/libtiledbsoma.*

# build
cd apis/python
pip install -v -e .

# check
python -c "import tiledbsoma.libtiledbsoma; print(tiledbsoma.libtiledbsoma.version())"

# install test data
cd -
./apis/python/tools/ingestor \
  --soco \
  -o test/soco \
  -n \
  data/pbmc3k_processed.h5ad \
  data/10x-pbmc-multiome-v1.0/subset_100_100.h5ad

# test
pytest -v --durations=0 libtiledbsoma


printf "\n\nActivate the tiledbsoma venv with this command:\n"
printf "\n    source test/tiledbsoma/bin/activate\n\n"
