#!/usr/bin/env bash

# A script to build and run the C++ library tests

set -eu -o pipefail

# cd to the top level directory of the repo
cd $(git rev-parse --show-toplevel)

cmake --build build/libtiledbsc --target unit_managed_query
cmake --build build/libtiledbsc --target unit_buffer_set
cmake --build build/libtiledbsc --target unit_sc
cmake --build build/libtiledbsc --target test
