# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_sdf <- function(uri) {
    invisible(.Call(`_tiledbsoma_test_sdf`, uri))
}

#' @rdname get_table
#' @export
get_column_names <- function(uri) {
    .Call(`_tiledbsoma_get_column_names`, uri)
}

export_column <- function(uri, colname, schemaxp, arrayxp) {
    .Call(`_tiledbsoma_export_column`, uri, colname, schemaxp, arrayxp)
}

#' @rdname get_table
#' @export
export_column_direct <- function(uri, colnames) {
    .Call(`_tiledbsoma_export_column_direct`, uri, colnames)
}

#' @rdname get_table
#' @export
export_arrow_array <- function(uri, colnames, qc = NULL, dim_points = NULL, dim_ranges = NULL, loglevel = "warn") {
    .Call(`_tiledbsoma_export_arrow_array`, uri, colnames, qc, dim_points, dim_ranges, loglevel)
}

#' @noRd
set_log_level <- function(level) {
    invisible(.Call(`_tiledbsoma_set_log_level`, level))
}

#' @rdname get_table
#' @export
nnz <- function(uri) {
    .Call(`_tiledbsoma_nnz`, uri)
}

#' @rdname get_table
#' @export
get_column_types <- function(uri, colnames) {
    .Call(`_tiledbsoma_get_column_types`, uri, colnames)
}

