# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createSchemaFromArrow <- function(uri, nasp, nadimap, nadimsp, sparse, datatype, pclst, ctxxp, tsvec = NULL) {
    invisible(.Call(`_tiledbsoma_createSchemaFromArrow`, uri, nasp, nadimap, nadimsp, sparse, datatype, pclst, ctxxp, tsvec))
}

createSchemaForNDArray <- function(uri, format, shape, soma_type, pclst, ctxxp, tsvec = NULL) {
    invisible(.Call(`_tiledbsoma_createSchemaForNDArray`, uri, format, shape, soma_type, pclst, ctxxp, tsvec))
}

writeArrayFromArrow <- function(soma_array, naap, nasp, arraytype = "") {
    invisible(.Call(`_tiledbsoma_writeArrayFromArrow`, soma_array, naap, nasp, arraytype))
}

c_group_create <- function(uri, type, ctxxp, timestamp = NULL) {
    invisible(.Call(`_tiledbsoma_c_group_create`, uri, type, ctxxp, timestamp))
}

c_group_open <- function(uri, type, ctxxp, timestamp = NULL) {
    .Call(`_tiledbsoma_c_group_open`, uri, type, ctxxp, timestamp)
}

c_group_member_count <- function(xp) {
    .Call(`_tiledbsoma_c_group_member_count`, xp)
}

c_group_members <- function(xp) {
    .Call(`_tiledbsoma_c_group_members`, xp)
}

c_group_get_metadata <- function(xp) {
    .Call(`_tiledbsoma_c_group_get_metadata`, xp)
}

c_group_close <- function(xp) {
    invisible(.Call(`_tiledbsoma_c_group_close`, xp))
}

c_group_set <- function(xp, uri, uri_type_int, name, soma_type) {
    invisible(.Call(`_tiledbsoma_c_group_set`, xp, uri, uri_type_int, name, soma_type))
}

c_group_remove_member <- function(xp, name) {
    invisible(.Call(`_tiledbsoma_c_group_remove_member`, xp, name))
}

c_group_put_metadata <- function(xp, key, obj) {
    invisible(.Call(`_tiledbsoma_c_group_put_metadata`, xp, key, obj))
}

get_metadata_num <- function(uri, is_array, ctxxp) {
    .Call(`_tiledbsoma_get_metadata_num`, uri, is_array, ctxxp)
}

get_all_metadata <- function(uri, is_array, ctxxp) {
    .Call(`_tiledbsoma_get_all_metadata`, uri, is_array, ctxxp)
}

get_metadata <- function(uri, key, is_array, ctxxp) {
    .Call(`_tiledbsoma_get_metadata`, uri, key, is_array, ctxxp)
}

has_metadata <- function(uri, key, is_array, ctxxp) {
    .Call(`_tiledbsoma_has_metadata`, uri, key, is_array, ctxxp)
}

delete_metadata <- function(uri, key, is_array, ctxxp) {
    invisible(.Call(`_tiledbsoma_delete_metadata`, uri, key, is_array, ctxxp))
}

set_metadata <- function(uri, key, valuesxp, type, is_array, ctxxp, tsvec = NULL) {
    invisible(.Call(`_tiledbsoma_set_metadata`, uri, key, valuesxp, type, is_array, ctxxp, tsvec))
}

libtiledbsoma_empty_query_condition <- function(ctxxp) {
    .Call(`_tiledbsoma_libtiledbsoma_empty_query_condition`, ctxxp)
}

libtiledbsoma_query_condition_from_triple <- function(query_cond, attr_name, condition_value, arrow_type_name, cond_op_string) {
    invisible(.Call(`_tiledbsoma_libtiledbsoma_query_condition_from_triple`, query_cond, attr_name, condition_value, arrow_type_name, cond_op_string))
}

libtiledbsoma_query_condition_combine <- function(lhs, rhs, str) {
    .Call(`_tiledbsoma_libtiledbsoma_query_condition_combine`, lhs, rhs, str)
}

libtiledbsoma_query_condition_in_nin <- function(ctxxp, attr_name, op_name, values) {
    .Call(`_tiledbsoma_libtiledbsoma_query_condition_in_nin`, ctxxp, attr_name, op_name, values)
}

reindex_create <- function() {
    .Call(`_tiledbsoma_reindex_create`)
}

reindex_map <- function(idx, nvec) {
    .Call(`_tiledbsoma_reindex_map`, idx, nvec)
}

reindex_lookup <- function(idx, kvec) {
    .Call(`_tiledbsoma_reindex_lookup`, idx, kvec)
}

soma_array_reader_impl <- function(uri, ctxxp, colnames = NULL, qc = NULL, dim_points = NULL, dim_ranges = NULL, batch_size = "auto", result_order = "auto", loglevel = "auto", timestamprange = NULL) {
    .Call(`_tiledbsoma_soma_array_reader`, uri, ctxxp, colnames, qc, dim_points, dim_ranges, batch_size, result_order, loglevel, timestamprange)
}

#' Set TileDB-SOMA Logging Level
#'
#' Set the logging level for the \R package and underlying C++ library
#'
#' @param level A character value with logging level. May be \dQuote{trace}, \dQuote{debug}, \dQuote{info},
#' or \dQuote{warn}
#'
#' @return Invisibly returns \code{NULL}
#'
#' @export
#'
set_log_level <- function(level) {
    invisible(.Call(`_tiledbsoma_set_log_level`, level))
}

#' Set a trace message
#'
#' @param msg The message to set with level 'trace'
#'
#' @return Invisibly returns \code{NULL}
#'
#' @noRd
#'
soma_trace <- function(msg) {
    invisible(.Call(`_tiledbsoma_soma_trace`, msg))
}

#' Set a debug message
#'
#' @param msg The message to set with level 'debug'
#'
#' @return Invisibly returns \code{NULL}
#'
#' @noRd
#'
soma_debug <- function(msg) {
    invisible(.Call(`_tiledbsoma_soma_debug`, msg))
}

#' Set a info message
#'
#' @param msg The message to set with level 'info'
#'
#' @return Invisibly returns \code{NULL}
#'
#' @noRd
#'
soma_info <- function(msg) {
    invisible(.Call(`_tiledbsoma_soma_info`, msg))
}

#' Set a warn message
#'
#' @param msg The message to set with level 'warn'
#'
#' @return Invisibly returns \code{NULL}
#'
#' @noRd
#'
soma_warn <- function(msg) {
    invisible(.Call(`_tiledbsoma_soma_warn`, msg))
}

nnz <- function(array) {
    .Call(`_tiledbsoma_nnz`, array)
}

check_arrow_schema_tag <- function(xp) {
    .Call(`_tiledbsoma_check_arrow_schema_tag`, xp)
}

check_arrow_array_tag <- function(xp) {
    .Call(`_tiledbsoma_check_arrow_array_tag`, xp)
}

shape <- function(array) {
    .Call(`_tiledbsoma_shape`, array)
}

maxshape <- function(array) {
    .Call(`_tiledbsoma_maxshape`, array)
}

non_empty_domain <- function(array) {
    .Call(`_tiledbsoma_non_empty_domain`, array)
}

domain <- function(dataframe) {
    .Call(`_tiledbsoma_domain`, dataframe)
}

maxdomain <- function(dataframe) {
    .Call(`_tiledbsoma_maxdomain`, dataframe)
}

maybe_soma_joinid_shape <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_maybe_soma_joinid_shape`, uri, ctxxp)
}

maybe_soma_joinid_maxshape <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_maybe_soma_joinid_maxshape`, uri, ctxxp)
}

has_current_domain <- function(array) {
    .Call(`_tiledbsoma_has_current_domain`, array)
}

ndim <- function(array) {
    .Call(`_tiledbsoma_ndim`, array)
}

c_dimnames <- function(array) {
    .Call(`_tiledbsoma_c_dimnames`, array)
}

c_attrnames <- function(array) {
    .Call(`_tiledbsoma_c_attrnames`, array)
}

c_schema <- function(array) {
    .Call(`_tiledbsoma_c_schema`, array)
}

c_is_sparse <- function(array) {
    .Call(`_tiledbsoma_c_is_sparse`, array)
}

c_allows_dups <- function(array) {
    .Call(`_tiledbsoma_c_allows_dups`, array)
}

c_capacity <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_c_capacity`, uri, ctxxp)
}

c_tile_order <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_c_tile_order`, uri, ctxxp)
}

c_cell_order <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_c_cell_order`, uri, ctxxp)
}

c_schema_filters <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_c_schema_filters`, uri, ctxxp)
}

c_attributes <- function(array) {
    .Call(`_tiledbsoma_c_attributes`, array)
}

c_attributes_enumerated <- function(dataframe) {
    .Call(`_tiledbsoma_c_attributes_enumerated`, dataframe)
}

c_attribute_enumeration_levels <- function(dataframe, name) {
    .Call(`_tiledbsoma_c_attribute_enumeration_levels`, dataframe, name)
}

c_domain <- function(array) {
    .Call(`_tiledbsoma_c_domain`, array)
}

resize <- function(ndarray, new_shape, function_name_for_messages, check_only) {
    .Call(`_tiledbsoma_resize`, ndarray, new_shape, function_name_for_messages, check_only)
}

resize_soma_joinid_shape <- function(dataframe, new_shape, function_name_for_messages) {
    invisible(.Call(`_tiledbsoma_resize_soma_joinid_shape`, dataframe, new_shape, function_name_for_messages))
}

tiledbsoma_upgrade_shape <- function(ndarray, new_shape, function_name_for_messages, check_only) {
    .Call(`_tiledbsoma_tiledbsoma_upgrade_shape`, ndarray, new_shape, function_name_for_messages, check_only)
}

upgrade_or_change_domain <- function(dataframe, is_change_domain, nadimap, nadimsp, function_name_for_messages, check_only) {
    .Call(`_tiledbsoma_upgrade_or_change_domain`, dataframe, is_change_domain, nadimap, nadimsp, function_name_for_messages, check_only)
}

c_update_dataframe_schema <- function(dataframe, column_names_to_drop, add_cols_types, add_cols_enum_value_types, add_cols_enum_ordered) {
    invisible(.Call(`_tiledbsoma_c_update_dataframe_schema`, dataframe, column_names_to_drop, add_cols_types, add_cols_enum_value_types, add_cols_enum_ordered))
}

mq_setup <- function(soma_array, colnames = NULL, qc = NULL, dim_points = NULL, dim_ranges = NULL, batch_size = "auto", result_order = "auto", loglevel = "auto") {
    .Call(`_tiledbsoma_mq_setup`, soma_array, colnames, qc, dim_points, dim_ranges, batch_size, result_order, loglevel)
}

mq_complete <- function(mq) {
    .Call(`_tiledbsoma_mq_complete`, mq)
}

create_empty_arrow_table <- function() {
    .Call(`_tiledbsoma_create_empty_arrow_table`)
}

mq_next <- function(mq) {
    .Call(`_tiledbsoma_mq_next`, mq)
}

mq_reset <- function(mq) {
    invisible(.Call(`_tiledbsoma_mq_reset`, mq))
}

mq_set_dim_points <- function(mq, dim, points) {
    invisible(.Call(`_tiledbsoma_mq_set_dim_points`, mq, dim, points))
}

#' TileDB SOMA Statistics
#'
#' These functions expose the TileDB Core functionality for performance
#'  measurements and statistics
#'
#' \itemize{
#'  \item \code{tiledbsoma_stats_enable()}/\code{tiledbsoma_stats_disable()}:
#'   Enable and disable TielDB's internal statistics
#'  \item \code{tiledbsoma_stats_reset()}: Reset all statistics to \code{0}
#'  \item \code{tiledbsoma_stats_dump()}: Dump all statistics as a JSON string
#'  \item \code{tiledbsoma_stats_show()}: Pretty-print the JSON statistics
#' }
#'
#' @return \code{tiledbsoma_stats_show()}: a single-length character vector
#' with the TileDB statistics encoded in JSON format
#'
#' @return All other functions invisibly return \code{NULL}
#'
#' @name tiledbsoma_stats
#'
#' @export
#'
tiledbsoma_stats_enable <- function() {
    invisible(.Call(`_tiledbsoma_tiledbsoma_stats_enable`))
}

#' @rdname tiledbsoma_stats
#'
#' @export
#'
tiledbsoma_stats_disable <- function() {
    invisible(.Call(`_tiledbsoma_tiledbsoma_stats_disable`))
}

#' @rdname tiledbsoma_stats
#'
#' @export
#'
tiledbsoma_stats_reset <- function() {
    invisible(.Call(`_tiledbsoma_tiledbsoma_stats_reset`))
}

#' @rdname tiledbsoma_stats
#'
#' @export
#'
tiledbsoma_stats_dump <- function() {
    .Call(`_tiledbsoma_tiledbsoma_stats_dump`)
}

libtiledbsoma_version <- function(compact = FALSE, major_minor_only = FALSE) {
    .Call(`_tiledbsoma_libtiledbsoma_version`, compact, major_minor_only)
}

tiledb_embedded_version <- function() {
    .Call(`_tiledbsoma_tiledb_embedded_version`)
}

tiledb_datatype_max_value <- function(datatype) {
    .Call(`_tiledbsoma_tiledb_datatype_max_value`, datatype)
}

get_soma_object_type <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_get_soma_object_type`, uri, ctxxp)
}

get_tiledb_object_type <- function(uri, ctxxp) {
    .Call(`_tiledbsoma_get_tiledb_object_type`, uri, ctxxp)
}

create_soma_context <- function(config = NULL) {
    .Call(`_tiledbsoma_create_soma_context`, config)
}

get_config_from_soma_context <- function(soma_context) {
    .Call(`_tiledbsoma_get_config_from_soma_context`, soma_context)
}

get_data_protocol_from_soma_context <- function(soma_context, uri) {
    .Call(`_tiledbsoma_get_data_protocol_from_soma_context`, soma_context, uri)
}

soma_object_get_metadata <- function(soma_object) {
    .Call(`_tiledbsoma_soma_object_get_metadata`, soma_object)
}

soma_object_close <- function(soma_object) {
    invisible(.Call(`_tiledbsoma_soma_object_close`, soma_object))
}

soma_object_is_open <- function(soma_object) {
    .Call(`_tiledbsoma_soma_object_is_open`, soma_object)
}

soma_object_open_mode <- function(dataframe) {
    .Call(`_tiledbsoma_soma_object_open_mode`, dataframe)
}

open_dataframe_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_dataframe_handle`, uri, mode, soma_context, tiledb_timestamp)
}

open_sparse_ndarray_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_sparse_ndarray_handle`, uri, mode, soma_context, tiledb_timestamp)
}

open_dense_ndarray_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_dense_ndarray_handle`, uri, mode, soma_context, tiledb_timestamp)
}

open_collection_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_collection_handle`, uri, mode, soma_context, tiledb_timestamp)
}

open_measurement_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_measurement_handle`, uri, mode, soma_context, tiledb_timestamp)
}

open_experiment_handle <- function(uri, mode, soma_context, tiledb_timestamp) {
    .Call(`_tiledbsoma_open_experiment_handle`, uri, mode, soma_context, tiledb_timestamp)
}

