#!/usr/bin/env python

import sys

import tiledb

import tiledbsoma
import tiledbsoma.util
import tiledbsoma.util_tiledb


# ----------------------------------------------------------------
def main():

    config = tiledb.Config()
    config["sm.mem.total_budget"] = 8 * 1024 ** 3
    config["sm.consolidation.buffer_size"] = 1024 ** 3
    ctx = tiledb.Ctx(config)

    if len(sys.argv) < 2:
        print(
            f"Usage: {sys.argv[0]} (one or more TileDB SOMA URIs)",
            file=sys.stderr,
        )
        sys.exit(1)

    for soma_uri in sys.argv[1:]:
        soma = tiledbsoma.SOMA(soma_uri)
        for key in soma.X.keys():
            x_uri = soma.X[key].uri
            tiledbsoma.util_tiledb.list_fragments(x_uri)
            s = tiledbsoma.util.get_start_stamp()
            print(f"START  consolidate {x_uri}")
            tiledb.consolidate(x_uri, ctx=ctx)
            tiledb.vacuum(x_uri, ctx=ctx)
            print(tiledbsoma.util.format_elapsed(s, f"FINISH consolidate {x_uri}"))


if __name__ == "__main__":
    main()
