#!/usr/bin/env python

"""
A simple driver for ingestion of anndata to a TileDB Experiment.

* Invoke this with one argument /path/to/some/somename.h5ad:
  o Output will be ./tiledbsoma-data/somename

* Invoke this with two arguments to specify input anndata HDF5 file
  and output TileDB group.
"""

import argparse
import os
import sys

import tiledb

import tiledbsoma
import tiledbsoma.exception
import tiledbsoma.io
import tiledbsoma.logging
import tiledbsoma.util


# ================================================================
def main():
    parser = argparse.ArgumentParser(
        description="Ingest SOMA data from anndata/h5ad into TileDB group structure"
    )
    parser.add_argument(
        "-q", "--quiet", help="decrease output verbosity", action="store_true"
    )
    parser.add_argument(
        "--debug", help="increase output verbosity", action="store_true"
    )
    parser.add_argument(
        "--ingest-mode",
        help="""Write mode (the default) writes all data, creating new layers if the soma already exists.

Resume mode skip data writes if data are within MBRs of the existing soma.
This is useful for continuing after a partial/interrupted previous upload.

Schema-only mode creates groups and array schema, without writing array data.
This is useful as a prep-step for parallel append-ingest of multiple H5ADs to a single soma.""",
        choices=["write", "schema_only", "schema-only", "resume"],
        default=["write"],
        nargs=1,
    )
    parser.add_argument(
        "-n",
        help="All arguments after flags are treated as input paths",
        action="store_true",
    )
    parser.add_argument(
        "-o",
        help="Specify output directory to contain the SOMAs",
        type=str,
        default=".",
    )
    parser.add_argument(
        "--soco",
        help="Write the SOMA and also append to a Collection there",
        action="store_true",
    )
    parser.add_argument(
        "-r",
        "--relative",
        help="""
* If `false` then the group will remember the absolute paths of each member array/subgroup. For
ingesting to TileDB Cloud, this is necessary.

* If `true` then the group will have the relative pth of the member. For TileDB Cloud, this
is never the right thing to do. For local-disk storage, this is essential if you want to move
a SOMA to another directory and have it be able access its members.

* If `auto`, then we select `relative=False` if the URI starts with `tiledb://`, else we
select `relative=True`. (This is the default.)
""",
        choices=["true", "false", "auto"],
        nargs=1,
    )
    parser.add_argument(
        "paths",
        type=str,
        help="One for specified input with default output path, or two to specify input and output paths, or multiple input paths if -n is specified",
        nargs="*",
    )
    args = parser.parse_args()

    write_soco = args.soco
    if args.debug:
        tiledbsoma.logging.debug()
    elif not args.quiet:
        tiledbsoma.logging.info()

    if args.relative is None:
        rel_member_uris = None
    else:
        relative = args.relative[0]
        if relative == "true":
            rel_member_uris = True
        elif relative == "false":
            rel_member_uris = False
        elif relative == "auto":
            rel_member_uris = None
        else:
            raise tiledbsoma.exception.SOMAError(f"Internal coding error in {__file__}")

    tiledb_platform_config = tiledbsoma.TileDBPlatformConfig(
        member_uris_are_relative=rel_member_uris
    )
    soco_dir = args.o.rstrip("/")

    if args.n:
        if len(args.paths) < 1:
            parser.print_help(file=sys.stderr)
            sys.exit(1)
        for input_path in args.paths:
            # Example 'anndata/pbmc3k_processed.h5ad' -> 'tiledbsoma-data/pbmc3k_processed'
            output_path = os.path.join(
                soco_dir, os.path.splitext(os.path.basename(input_path))[0]
            )
            ingest_one(
                input_path=input_path,
                output_path=output_path,
                ingest_mode=args.ingest_mode[0],
                tiledb_platform_config=tiledb_platform_config,
                write_soco=write_soco,
                soco_dir=soco_dir,
            )
    else:
        if len(args.paths) == 0:
            input_path = "anndata/pbmc-small.h5ad"
            output_path = os.path.join(soco_dir, "pbmc-small")
            ingest_one(
                input_path=input_path,
                output_path=output_path,
                ingest_mode=args.ingest_mode[0],
                tiledb_platform_config=tiledb_platform_config,
                write_soco=write_soco,
                soco_dir=soco_dir,
            )
        elif len(args.paths) == 1:
            input_path = args.paths[0]
            # Example 'anndata/pbmc3k_processed.h5ad' -> 'tiledbsoma-data/pbmc3k_processed'
            output_path = os.path.join(
                soco_dir, os.path.splitext(os.path.basename(input_path))[0]
            )
            ingest_one(
                input_path=input_path,
                output_path=output_path,
                ingest_mode=args.ingest_mode[0],
                tiledb_platform_config=tiledb_platform_config,
                write_soco=write_soco,
                soco_dir=soco_dir,
            )
        elif len(args.paths) == 2:
            input_path = args.paths[0]
            output_path = args.paths[1]
            ingest_one(
                input_path=input_path,
                output_path=output_path,
                ingest_mode=args.ingest_mode[0],
                tiledb_platform_config=tiledb_platform_config,
                write_soco=write_soco,
                soco_dir=soco_dir,
            )
        else:
            parser.print_help(file=sys.stderr)
            sys.exit(1)


# ================================================================
def ingest_one(
    *,
    input_path: str,
    output_path: str,
    ingest_mode: str,
    tiledb_platform_config: tiledbsoma.TileDBPlatformConfig,
    write_soco: bool,
    soco_dir: str,
):
    # This will be a very common command-line thing to do since the arg is `--ingest-mode` not
    # `--ingest_mode`. Let's be kind and supportive about it.
    if ingest_mode == "schema-only":
        ingest_mode = "schema_only"

    assert ingest_mode in tiledbsoma.types.INGEST_MODES

    # Check that the input exists.
    vfs = tiledb.VFS()
    if not vfs.is_file(input_path):
        # Print this neatly and exit neatly, to avoid a multi-line stack trace otherwise.
        tiledbsoma.logging.logger.error(f"Input path not found: {input_path}")
        sys.exit(1)

    # Prepare to write the output.
    # This is for local-disk use only -- for S3-backed tiledb://... URIs we should
    # use tiledb.vfs to remove any priors, and/or make use of a tiledb `overwrite` flag.
    parent = os.path.dirname(output_path.rstrip("/"))
    if parent != "":
        if tiledbsoma.util.is_local_path(parent):
            if not os.path.exists(parent):
                os.mkdir(parent)

    exp = tiledbsoma.Experiment(
        uri=output_path, tiledb_platform_config=tiledb_platform_config
    )
    exp_name = os.path.splitext(os.path.basename(output_path))[0]

    tiledbsoma.io.from_h5ad(exp, input_path, "RNA", ingest_mode=ingest_mode)

    if write_soco:
        soco = tiledbsoma.Collection(
            soco_dir, tiledb_platform_config=tiledb_platform_config
        )
        if not soco.exists():
            soco.create()
        if not soco.exists():
            raise Exception(f"Could not create SOCO at {soco.uri}")
        soco.set(exp_name, exp)

        tiledbsoma.logging.logger.info("")
        tiledbsoma.logging.logger.info(
            f"Added Experiment {exp_name} to Collection {soco_dir}"
        )


# ================================================================
if __name__ == "__main__":
    main()
