#!/usr/bin/env python -i

# Invoke this with, for example,
#
#   peek-soco ./soma-collection
#
# -- then you can inspect the SOMACollection object

import tiledb
import tiledbsc as t
import sys, os

import anndata
import anndata as ad  # so we can type it either way
import pandas
import pandas as pd  # so we can type it either way
import numpy
import numpy as np  # so we can type it either way
import scipy

from typing import List, Dict

if len(sys.argv) == 1:
    soco_path = "soma-collection"
elif len(sys.argv) == 2:
    soco_path = sys.argv[1]
else:
    print(f"{sys.argv[0]}: need just one soma-collection path.", file=sys.stderr)
    sys.exit(1)

soco = t.SOMACollection(soco_path)

# Interact at the Python prompt now
