#!/usr/bin/env python -i

# Invoke this with, for example,
#
#   python -i peek-ann.py anndata/pbmc3k_processed.h5ad
#
# -- then you can inspect the anndata object.

import tiledb
import tiledbsc
import tiledbsc.io
import sys, os

import anndata
import anndata as ad  # so we can type it either way

import pandas
import pandas as pd  # so we can type it either way
import numpy
import numpy as np  # so we can type it either way
import scipy

if len(sys.argv) == 1:
    input_path = "anndata/pbmc-small.h5ad"
elif len(sys.argv) == 2:
    input_path = sys.argv[1]
else:
    print(f"{sys.argv[0]}: need just one .h5ad file name.", file=sys.stderr)
    sys.exit(1)

ann = anndata.read_h5ad(input_path)

# Interact at the prompt now:
# * ann.X
# * ann.obs.keys()
# * ann.obs.head()
# * ann.obs.index
# * ann.obs.values
# * etc
