#!/usr/bin/env python

# ================================================================
# Sample usage:
#
# populate-soco -o my-collection -a ~/scdata/corpus/*
# ================================================================

import argparse
import os
import sys

import tiledbsc


# ================================================================
def main():
    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    parser = argparse.ArgumentParser(
        description="Populate a SOMA collection from a list of SOMAs."
    )
    parser.add_argument(
        "-o",
        help="Specify output directory to contain the somas",
        type=str,
        default="./soma-collection",
    )
    parser.add_argument(
        "-a",
        "--add",
        help="Add specified SOMA URI(s) to the collection",
        action="store_true",
    )
    parser.add_argument(
        "-r",
        "--remove",
        help="Remove specified SOMA URI(s) from the collection",
        action="store_true",
    )
    parser.add_argument(
        "-l",
        "--list",
        help="List the SOMA URI(s) in the collection",
        action="store_true",
    )
    parser.add_argument(
        "paths", type=str, help="Paths to one or more SOMA directories.", nargs="*"
    )
    args = parser.parse_args()

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    collection_path = args.o.rstrip("/")
    soco = tiledbsc.SOMACollection(collection_path)

    count = 0
    if args.add:
        count += 1
    if args.remove:
        count += 1
    if args.list:
        count += 1
    if count != 1:
        print(f"{os.path.basename(sys.argv[0])}: need just one of -a, -r, or -l.")
        sys.exit(1)

    if args.add or args.remove:
        if len(args.paths) < 1:
            parser.print_help(file=sys.stderr)
            sys.exit(1)
    else:
        if len(args.paths) > 0:
            parser.print_help(file=sys.stderr)
            sys.exit(1)

    if args.add:
        for soma_uri in args.paths:
            soma_uri = soma_uri.rstrip("/")
            name = os.path.basename(soma_uri)
            soma = tiledbsc.SOMA(uri=soma_uri, name=name, parent=soco)
            print(f"Adding {name} to {soma_uri}")
            soco.add(soma)

    if args.remove:
        for soma_uri in args.paths:
            soma_uri = soma_uri.rstrip("/")
            name = os.path.basename(soma_uri)
            soma = tiledbsc.SOMA(uri=soma_uri, name=name, parent=soco)
            print(f"Removing {name} from {soma_uri}")
            soco.remove(soma)

    if args.list:
        for soma in soco:
            print("%-30s %s" % (soma.name, soma.uri))


# ================================================================
if __name__ == "__main__":
    main()
