name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled
    paths-ignore:
      - '_quarto.yml'
      - 'quarto-materials/*'
      - '**/.md'

jobs:
  backport:
    runs-on: ubuntu-24.04
    name: Backport
    steps:
      - name: Backport
        if: >
          github.event.pull_request.merged
          && (
            github.event.action == 'closed'
            || (
              github.event.action == 'labeled'
              && contains(github.event.label.name, 'backport')
            )
          )
        uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
