name: TileDB-SOMA Python CI (Pull-request)

on:
  pull_request:
    paths:
      - "libtiledbsoma/**"
      - "apis/python/**"
      - "!**.md"
      - ".github/workflows/ci-pr-python.yml"
      - ".github/workflows/test-python.yml"
  workflow_dispatch:

jobs:
  python-tests:
    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-24.04, macos-latest]
        python-version: ["3.9", "3.12", "3.13"]
        include:
          - os: ubuntu-24.04
            cc: gcc-13
            cxx: g++-13
          - os: macos-latest
            cc: clang
            cxx: clang++
            extra_pytest_options: "-m 'not medium_runner'"
    uses: ./.github/workflows/test-python.yml
    with:
      os: ${{ matrix.os }}
      python_version: ${{ matrix.python-version }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      report_codecov: ${{ matrix.os == 'ubuntu-24.04' && matrix.python-version == '3.12' }}
      extra_pytest_options: ${{ matrix.extra_pytest_options }}
    secrets: inherit
