name: libtiledbsoma ASAN

on:
  schedule:
    - cron: 20 8 * * 0
  workflow_dispatch:

jobs:
  asan:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout TileDB-SOMA
      uses: actions/checkout@v4
    - name: Build libtiledbsoma
      run: ./scripts/bld --build=ASAN --no-tiledb-deprecated=true --werror=true
    - name: Run libTileDB-SOMA unittests
      run: ctest --test-dir build/libtiledbsoma -C ASAN --verbose --rerun-failed --output-on-failure
