name: TileDB-SOMA docker builds
on:
  workflow_dispatch:
jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        idx: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24 ]
    name: 'Ubuntu src ARM #${{ matrix.idx }}'
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        run: |
          cmd=(docker build -f ubuntu-src.dockerfile -t ubuntu-src .)
          echo "Running: ${cmd[*]}"
          "${cmd[@]}"
        working-directory: docker
      - run: docker run ubuntu-src
        working-directory: docker
